### PR TITLE
Fix composer config and unit tests

### PR DESCRIPTION
**Pull request by HanXHX**
- Do not add vendor dir in versionning
- Fix autoloading dev
- Add ext-xml dep
- Remove hard dependency to PHP 7.2
- Add PHPUnit dev dep and fix legacy unit tests

### CODE REVIEW

**Comment by skjnldsv** [comment]
Please sign the DCO :)
https://github.com/nextcloud/updater_server/pull/839/checks?check_run_id=11720525838

**Review by nickvergessen — CHANGES_REQUESTED** [review]
> Remove hard dependency to PHP 7.2

Production still runs it, so blocking for now.

**Comment by nickvergessen** [comment]
> With my patch, composer can run on "all" PHP version.

But anyone updating a dependency might bump it to a version that is not compatible with 7.2 anymore.

**Comment by nickvergessen** [comment]
> - This project must be run only on PHP 7.2 (eol 2020)?
> - No plan to support up to date PHP version?

That is not what the platform is about. Please see this documentation page: https://getcomposer.org/doc/06-config.md#platform
Platform specifies a minimum, not an "only version".

> - Is this project supposed to run properly with Nextcloud server with up to date PHP version?

This project here runs totally independent and is actually only run by us, not by admins running a Nextcloud Server 26 or whatever other version at home.

**Pull request closed without merging**
