### PR TITLE
feat(config): remove beta duplication

### PR DESCRIPTION
**Pull request by Altahrim**
Beta now fallback to stable if no version found.
It avoids to duplicate configuration from stable to beta

### CODE REVIEW

**Comment by blizzz** [comment]
I am a bit torn here. On the one hand yes, on the other hand I am not sure it improves the experience of adding beta release information.

**Comment by Altahrim** [comment]
I think it mainly improve the experience of adding stable releases as we don't have to duplicate the stable branch information.
I also allows for further improvements as I am able to generate the same file from a simpler one. Something like:
```php
$versions = [
	'28.0.3' => [
		'internalVersion' => '28.0.3.2',
		'signature' => 'WToO5cGwGRwv6UAO84jqBilEabOJFytls2oL4Pvja2y28I98IZpQdK9V11Gp7+mS
wEceiJaD9pFoUWcLkKT/VH8+apU9vP55/lcChDsab5k4e2mrIN0gKbUDdsFTr/Fl
IGqsRnrFBg7XrFSg0Mm3IYjEvSHWK/YlotG6VCfdZOKkEeW1uOLFDh0RVLx6fYeo
wH7EZIg+VnJkcJ8uqoy9+SM/ROV/rsa7p8UiLJLB7UKNNUFnCSiT2OpJzxxSPeL7
78rc8LM+fDj/K5kPwIHHfjOYaHfblGxjR1qhLyxak5JonSwT9D38l9uqk/DVUs2O
8AkppHJdBdSUvZnVM4fzaA==',
	],
	'29.0.0 beta 3' => [
		'internalVersion' => '29.0.0.9',
		'signature' => 'kDGkxgxbdbOk64ONHW7lbdm0WpMx43Cj5JrcQeLtwozeaCo/HH38bCYBZog7YVdg
GqwOsuI+QqRDySNazGwcViHn71397wt0MRBUWPGw7+hDO9YjHM+b9oCgjcHLmo+J
LWiWGlcS8LgqbBW1HKHxJQFP5rzpt9hy1sc4UNjgrnmG+/XdqTSXAlewSS3S2piw
jkw+ui4UKG46X1Mfs5inmpr/qI6+H10zXyHB4Vn5uEL3qA0Q676P61YpuwYcEVVa
SVI3kysesRh+1DUp7ErG9iCzlBXJhVsDvL5bzR87QwLgIiOVUFY+dhwkiRr08AHu
IwYSX8nWX9zpP3pl58PZQw==',
	],
 …
];

$majorVersions = [
	29 => [
		'minPHP' => '8.0'
	],
	28 => [
		'eol' => '2024-12',
		'minPHP' => '8.0'
	],
	…
];

**Review by blizzz — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
29 upgrade failure expected

**Comment by Altahrim** [comment]
It breaks EOL test (https://github.com/nextcloud/server/actions/runs/8371442609/job/22920497105?pr=44374)

**Pull request merged**
